#include "main.h"
#include "i2c.h"
#include "SSD1306_128x72.h"

#include <stdint.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

/*用于清零的常数组*/
uint8_t ClearArray[FULL_ARRAY_LENGTH + 1] = {0};

/*可自定义测试数组*/
uint8_t TestArray[] = {0,1};
uint8_t TestArrayLength  = sizeof(TestArray) / sizeof(TestArray[0]);
uint8_t TestArray2[128] = {0};//三角波测试数组

/*显存*/
uint8_t GRAM[128][9] = {0};

uint8_t InitCommandArray[] = {
    0xAE,       // 关闭显示（Display OFF）

    0xDA,       // 设置显示时钟分频比/振荡器频率
    0xF0,       // 参数：高4位振荡器频率0x8，低4位分频比0x0，默认稳定

    0xA8,       // 设置多路复用率（MUX Ratio）
    0x3F,       // 参数：0x3F = 63，对应64行显示

    0xD3,       // 设置显示偏移（Display Offset）
    0x00,       // 参数：0x00 = 无偏移

    0x40,       // 设置显示开始行（Display Start Line）第0行开始

    0xA1,       // 设置左右方向（Segment Re-map）
                // 0xA1 = 左右翻转，0xA0 = 正常方向
    0xC0,       // 设置上下方向（COM Output Scan Direction）
                // 0xC8 = 上下翻转，0xC0 = 正常方向

    0xDA,       // 设置COM引脚硬件配置（COM Pins Hardware Configuration）
    0x12,       // 参数：0x12 = alternative COM pin config，顺序扫描

    0x81,       // 设置对比度控制（Contrast Control）
    0xCF,       // 参数：0xCF = 对比度值，范围0x00~0xFF

    0xD9,       // 设置预充电周期（Pre-charge Period）
    0xF1,       // 参数：高4位PH = 0xF，低4位PL = 0x1，默认推荐值

    0xDB,       // 设置VCOMH电压取消选择级别（VCOMH Deselect Level）
    0x30,       // 参数：0x30 = ~0.83*VCC

    0xA4,       // 设置整个显示打开/关闭（Entire Display ON）
                // 0xA4 = 根据 RAM 显示，0xA5 = 全屏点亮

    0xA6,       // 设置正常/倒转显示（Normal/Inverse Display）
                // 0xA6 = 正常显示，0xA7 = 倒转显示

    0x20,       // 设置寻址模式
    0x00,       // 0x00 水平寻址(默认),0x01 垂直寻址,0x02 页寻址

    0x8D,       // 设置充电泵（Charge Pump Setting）
    0x14,       // 参数：0x14 = 充电泵开启

    0xAF        // 开启显示（Display ON）
};
//AI Generated by ChatGPT

/**
 * @brief 三角波测试数组初始化
 * 
 * @param TestArray 传入的待设置的数组的指针
 */
void Screen_InitTestArray(uint8_t* TestArray)
{
    for (int i = 0; i < 128; i++) {
        // 三角波1：周期32，幅度0..15
        uint8_t t1 = i % 32;
        if (t1 >= 16) t1 = 31 - t1;

        // 三角波2：周期20，幅度0..9
        uint8_t t2 = i % 20;
        if (t2 >= 10) t2 = 19 - t2;

        // 组合并缩放到 0..63（noise 范围 -1..1）
        int v = (t1 * 3) + (t2 * 2) + (rand() % 3 - 1);

        // 限制到 0..63
        if (v < 0) v = 0;
        if (v > 63) v = 63;

        TestArray[i] = (uint8_t)v;
    }
}

/**
 * @brief 初始化显示屏
 * 
 */
void Screen_Init()
{
    HAL_I2C_Master_Transmit(&hi2c1,ADDRESS,(uint8_t*)InitCommandArray,( sizeof(InitCommandArray) / sizeof(InitCommandArray[0]) ) ,HAL_MAX_DELAY);
}

/**
 * @brief 发送指令
 * 
 * @param Command 需要发送的指令
 */
void Screen_SendCommand(uint8_t Command)
{
    uint8_t CommandBuffer[2] = {0x00,Command};
    HAL_I2C_Master_Transmit(&hi2c1,ADDRESS,CommandBuffer,2,HAL_MAX_DELAY);
}

/**
 * @brief 发送数据
 * 
 * @param Data 需要发送的数据
 */
void Screen_SendData(uint8_t Data)
{
    uint8_t DataBuffer[2] = {0x40,Data};
    HAL_I2C_Master_Transmit(&hi2c1,ADDRESS,DataBuffer,2,HAL_MAX_DELAY);
}

/**
 * @brief 设置光标位置
 * 
 * @param x 横坐标,列,从左到右0-127
 * @param page 页,从下到上0-7
 */
void Screen_SetSite(uint8_t x, uint8_t page)
{
    Screen_SendCommand(0xB0 | page);//设置页
	Screen_SendCommand(0x10 | ( ( x & 0xF0 ) >> 4) );//行高地址
	Screen_SendCommand(0x00 | (x & 0x0F));//行低地址
}

/**
 * @brief 清屏函数
 */
void Screen_Clear()
{
    // for(int j = 0 ; j < 8 ; j ++)
    // {
    //     for(int i = 0 ; i < 128 ; i ++)
    //     {
    //         Screen_SetSite(i,j);
    //         Screen_SendData(0);
    //     }
    // }
    ClearArray[0] = 0x40;
    HAL_I2C_Master_Transmit(&hi2c1, ADDRESS, (uint8_t*)ClearArray, FULL_ARRAY_LENGTH + 1, HAL_MAX_DELAY);
}

/**
 * @brief 将数字处理成能在显示屏上显示的版本,返回一个带页地址和移位数的结构体
 * 
 * @param Number 要处理的数字
 * @note Pixel类型定义详见头文件
 */
Pixel Screen_NumberProcess(uint8_t Number)
{
    Pixel pixel;
    pixel.Page = ( Number / 8 ); //求页地址,应为0. . .7
    pixel.Offset = Number % 8;//求本页偏移量

    return pixel;
}

/**
 * @brief 根据给定的数组设置显存
 * 
 * @param Array 指定的图像数组指针
 * @param ArrayLength 图像数组长度
 * @param GRamArray 显存数组
 * @param LineArray 线数组
 */
void Screen_GramSetValue(uint8_t* Array, uint8_t ArrayLength, uint8_t (*GRamArray)[9])
{

    /*线数组*/
    uint8_t LineArray1[FULL_ARRAY_LENGTH - 128] = {0};
    uint8_t LineArray2[128 + 1] = {0};

    /*调试用变量*/
    uint8_t Debug_Offset    = 0;
    uint8_t Debug_Page      = 0;

    /*对下标为0的元素,正常离散点显示*/
    GRamArray[0][Screen_NumberProcess(Array[0]).Page] = 1 << Screen_NumberProcess(Array[0]).Offset;

    /*遍历下标不为0的元素*/
    for (int ColumnIndex = 1 ; ColumnIndex < ArrayLength ; ColumnIndex ++)
    {

        Pixel CurrentPixel  = Screen_NumberProcess(Array[ColumnIndex]);//当前数组值
        // Pixel LastPixel     = Screen_NumberProcess(Array[ColumnIndex - 1]);//上一数组值

        /*调试用变量赋值*/
        Debug_Offset = Screen_NumberProcess(Array[ColumnIndex]).Offset;
        Debug_Page   = Screen_NumberProcess(Array[ColumnIndex]).Page;

        /*正常离散点显示*/
        GRamArray[ColumnIndex][CurrentPixel.Page] = 1 << CurrentPixel.Offset;

        // /*中间补齐*/

        // /*当前一个值大于后一个值*/
        // if (Array[ColumnIndex - 1] > Array[ColumnIndex])
        // {

        //     /*当两值不在同一页*/
        //     if (CurrentPixel.Page != LastPixel.Page)
        //     {

        //         /*对上一值所在页*/
        //         GRamArray[ColumnIndex - 1][LastPixel.Page] = 0xFF << (LastPixel.Offset);//按照地址访问显存,补齐

        //         /*对中间页*/
        //         // uint8_t DeltaPage = CurrentPixel.Page - LastPixel.Page;//获取页差

        //         for (uint8_t PageIndex = LastPixel.Page + 1 ; PageIndex < CurrentPixel.Page ; PageIndex++)
        //         {

        //             GRamArray[ColumnIndex][PageIndex] = 0xFF;//中间页全亮

        //         }

        //         /*对当前值所在页*/
        //         GRamArray[ColumnIndex][CurrentPixel.Page] = 0xFF >> ( 8 - CurrentPixel.Offset );

        //     /*当在同一页*/
        //     } else {

        //         /*上一值正常显示*/
        //         /*对中间进行插入补齐*/
        //         uint8_t DeltaOffset = CurrentPixel.Offset - LastPixel.Offset;//获取偏移量差值

        //         uint8_t FillData = 1 << (LastPixel.Offset + 1);//填充用数据:将上一位数正常发送时发送的数据复制,并且向左移一位(偏移量+1).

        //         uint8_t TempData = FillData;//临时数据初始值等于填充用数据

        //         for(uint8_t OffsetValue = 1 ; OffsetValue < DeltaOffset ; OffsetValue ++)//执行偏移循环,次数为两数字偏移差减去一,因为首先在CopyData偏移了一位
        //         {

        //             TempData = (TempData << 1) | FillData;//每次循环左移一位同时与上Copydata,算是补全中间了

        //         }

        //         /*补齐赋值*/
        //         GRamArray[ColumnIndex][CurrentPixel.Page] = TempData;

        //     }

        // /*当前一个值等于后一个值*/
        // } else if (Array[ColumnIndex - 1] == Array[ColumnIndex]){

        //     /*正常显存赋值*/
        //     GRamArray[ColumnIndex][CurrentPixel.Page] = 1 << CurrentPixel.Offset; 

        // /*当前一个值小于后一个值*/
        // } else if (Array[ColumnIndex - 1] < Array[ColumnIndex]){

        //     /*当两值不在同一页*/
        //     if (CurrentPixel.Page != LastPixel.Page)
        //     {

        //         /*中间补齐*/

        //         /*对上一值所在页*/
        //         GRamArray[ColumnIndex - 1][LastPixel.Page] = 0 << (LastPixel.Offset);//按照地址访问显存,补齐

        //         /*对中间页*/
        //         // uint8_t DeltaPage = LastPixel.Page - CurrentPixel.Page;//获取页差

        //         for (uint8_t PageIndex = LastPixel.Page - 1 ; PageIndex > CurrentPixel.Page ; PageIndex--)
        //         {

        //             GRamArray[ColumnIndex][PageIndex] = 0xFF;//中间页全亮

        //         }

        //         /*对当前值所在页*/
        //         GRamArray[ColumnIndex][CurrentPixel.Page] = 0xFF << (CurrentPixel.Offset);

        //     /*当在同一页*/
        //     } else {

        //         /*上一值正常显示*/
        //         /*对中间进行插入补齐*/
        //         uint8_t DeltaOffset = CurrentPixel.Offset - LastPixel.Offset;//获取偏移量差值

        //         uint8_t FillData = 1 << (LastPixel.Offset - 1);//填充用数据:将上一位数正常发送时发送的数据复制,并且向右移一位(偏移量-1).

        //         uint8_t TempData = FillData;//先将填充用数据赋值给临时数据初始值

        //         for(uint8_t OffsetValue = 1 ; OffsetValue < DeltaOffset ; OffsetValue ++)//执行偏移循环,次数为两数字偏移差减去一,因为首先在CopyData偏移了一位
        //         {

        //             TempData = (TempData >> 1) | FillData;//每次循环右移一位同时与上Copydata,算是补全中间了

        //         }

        //         /*补齐赋值*/
        //         GRamArray[ColumnIndex][CurrentPixel.Page] = TempData;

        //     }
        // }

    }

    /*线数组赋值*/

    /*第一线数组*/
    LineArray1[0] = 0x40;//数据字节标志位
    uint16_t Index1 = 1;

    for (uint8_t Line = 0 ; Line < 8 ; Line ++)//外层循环,遍历行(y)
    {

        for (uint8_t Column = 0 ; Column < 128 ; Column ++)//内层循环,遍历列(x)
        {

            LineArray1[Index1] = GRamArray[Column][Line];//线数组正式赋值
            Index1 ++;//下标自增

        }

    }

    /*第二线数组*/
    LineArray2[0] = 0x40;//数据字节标志位
    uint16_t Index2 = 1;

        for (uint8_t Column = 0 ; Column < 128 ; Column ++)//遍历列(x)
        {

            LineArray2[Index2] = GRamArray[Column][8];//线数组正式赋值
            Index2 ++;//下标自增

        }

    /*线数组发送*/

    /*光标归位*/
    Screen_SetSite(0,0);

    /*第一段*/
    HAL_I2C_Master_Transmit(&hi2c1, ADDRESS, LineArray1, sizeof(LineArray1) / sizeof(LineArray1[0]), HAL_MAX_DELAY);

    /*第二段*/
    HAL_I2C_Master_Transmit(&hi2c1, ADDRESS, LineArray2, sizeof(LineArray2) / sizeof(LineArray2[0]), HAL_MAX_DELAY);

    

}